// Code generated by entc, DO NOT EDIT.

package decision

import (
	"time"
)

const (
	// Label holds the string label denoting the decision type in the database.
	Label = "decision"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUntil holds the string denoting the until field in the database.
	FieldUntil = "until"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldScenario holds the string denoting the scenario field in the database.
	FieldScenario = "scenario"
	// FieldDecisionType holds the string denoting the decisiontype field in the database.
	FieldDecisionType = "decision_type"
	// FieldSourceIpStart holds the string denoting the sourceipstart field in the database.
	FieldSourceIpStart = "source_ip_start"
	// FieldSourceIpEnd holds the string denoting the sourceipend field in the database.
	FieldSourceIpEnd = "source_ip_end"
	// FieldSourceStr holds the string denoting the sourcestr field in the database.
	FieldSourceStr = "source_str"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the decision in the database.
	Table = "decisions"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "decisions"
	// OwnerInverseTable is the table name for the Signal entity.
	// It exists in this package in order to avoid circular dependency with the "signal" package.
	OwnerInverseTable = "signals"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "signal_decisions"
)

// Columns holds all SQL columns for decision fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUntil,
	FieldReason,
	FieldScenario,
	FieldDecisionType,
	FieldSourceIpStart,
	FieldSourceIpEnd,
	FieldSourceStr,
	FieldScope,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Decision type.
var ForeignKeys = []string{
	"signal_decisions",
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
)
