// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/crowdsecurity/crowdsec/cmd/api/ent/alert"
	"github.com/crowdsecurity/crowdsec/cmd/api/ent/decision"
	"github.com/crowdsecurity/crowdsec/cmd/api/ent/predicate"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// DecisionUpdate is the builder for updating Decision entities.
type DecisionUpdate struct {
	config
	hooks      []Hook
	mutation   *DecisionMutation
	predicates []predicate.Decision
}

// Where adds a new predicate for the builder.
func (du *DecisionUpdate) Where(ps ...predicate.Decision) *DecisionUpdate {
	du.predicates = append(du.predicates, ps...)
	return du
}

// SetCreatedAt sets the created_at field.
func (du *DecisionUpdate) SetCreatedAt(t time.Time) *DecisionUpdate {
	du.mutation.SetCreatedAt(t)
	return du
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (du *DecisionUpdate) SetNillableCreatedAt(t *time.Time) *DecisionUpdate {
	if t != nil {
		du.SetCreatedAt(*t)
	}
	return du
}

// SetUpdatedAt sets the updated_at field.
func (du *DecisionUpdate) SetUpdatedAt(t time.Time) *DecisionUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (du *DecisionUpdate) SetNillableUpdatedAt(t *time.Time) *DecisionUpdate {
	if t != nil {
		du.SetUpdatedAt(*t)
	}
	return du
}

// SetUntil sets the until field.
func (du *DecisionUpdate) SetUntil(t time.Time) *DecisionUpdate {
	du.mutation.SetUntil(t)
	return du
}

// SetScenario sets the scenario field.
func (du *DecisionUpdate) SetScenario(s string) *DecisionUpdate {
	du.mutation.SetScenario(s)
	return du
}

// SetDecisionType sets the decisionType field.
func (du *DecisionUpdate) SetDecisionType(s string) *DecisionUpdate {
	du.mutation.SetDecisionType(s)
	return du
}

// SetSourceIpStart sets the sourceIpStart field.
func (du *DecisionUpdate) SetSourceIpStart(i int) *DecisionUpdate {
	du.mutation.ResetSourceIpStart()
	du.mutation.SetSourceIpStart(i)
	return du
}

// SetNillableSourceIpStart sets the sourceIpStart field if the given value is not nil.
func (du *DecisionUpdate) SetNillableSourceIpStart(i *int) *DecisionUpdate {
	if i != nil {
		du.SetSourceIpStart(*i)
	}
	return du
}

// AddSourceIpStart adds i to sourceIpStart.
func (du *DecisionUpdate) AddSourceIpStart(i int) *DecisionUpdate {
	du.mutation.AddSourceIpStart(i)
	return du
}

// ClearSourceIpStart clears the value of sourceIpStart.
func (du *DecisionUpdate) ClearSourceIpStart() *DecisionUpdate {
	du.mutation.ClearSourceIpStart()
	return du
}

// SetSourceIpEnd sets the sourceIpEnd field.
func (du *DecisionUpdate) SetSourceIpEnd(i int) *DecisionUpdate {
	du.mutation.ResetSourceIpEnd()
	du.mutation.SetSourceIpEnd(i)
	return du
}

// SetNillableSourceIpEnd sets the sourceIpEnd field if the given value is not nil.
func (du *DecisionUpdate) SetNillableSourceIpEnd(i *int) *DecisionUpdate {
	if i != nil {
		du.SetSourceIpEnd(*i)
	}
	return du
}

// AddSourceIpEnd adds i to sourceIpEnd.
func (du *DecisionUpdate) AddSourceIpEnd(i int) *DecisionUpdate {
	du.mutation.AddSourceIpEnd(i)
	return du
}

// ClearSourceIpEnd clears the value of sourceIpEnd.
func (du *DecisionUpdate) ClearSourceIpEnd() *DecisionUpdate {
	du.mutation.ClearSourceIpEnd()
	return du
}

// SetSourceScope sets the sourceScope field.
func (du *DecisionUpdate) SetSourceScope(s string) *DecisionUpdate {
	du.mutation.SetSourceScope(s)
	return du
}

// SetSourceValue sets the sourceValue field.
func (du *DecisionUpdate) SetSourceValue(s string) *DecisionUpdate {
	du.mutation.SetSourceValue(s)
	return du
}

// SetOwnerID sets the owner edge to Alert by id.
func (du *DecisionUpdate) SetOwnerID(id int) *DecisionUpdate {
	du.mutation.SetOwnerID(id)
	return du
}

// SetNillableOwnerID sets the owner edge to Alert by id if the given value is not nil.
func (du *DecisionUpdate) SetNillableOwnerID(id *int) *DecisionUpdate {
	if id != nil {
		du = du.SetOwnerID(*id)
	}
	return du
}

// SetOwner sets the owner edge to Alert.
func (du *DecisionUpdate) SetOwner(a *Alert) *DecisionUpdate {
	return du.SetOwnerID(a.ID)
}

// Mutation returns the DecisionMutation object of the builder.
func (du *DecisionUpdate) Mutation() *DecisionMutation {
	return du.mutation
}

// ClearOwner clears the owner edge to Alert.
func (du *DecisionUpdate) ClearOwner() *DecisionUpdate {
	du.mutation.ClearOwner()
	return du
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (du *DecisionUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DecisionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DecisionUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DecisionUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DecisionUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DecisionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   decision.Table,
			Columns: decision.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: decision.FieldID,
			},
		},
	}
	if ps := du.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: decision.FieldCreatedAt,
		})
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: decision.FieldUpdatedAt,
		})
	}
	if value, ok := du.mutation.Until(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: decision.FieldUntil,
		})
	}
	if value, ok := du.mutation.Scenario(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldScenario,
		})
	}
	if value, ok := du.mutation.DecisionType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldDecisionType,
		})
	}
	if value, ok := du.mutation.SourceIpStart(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpStart,
		})
	}
	if value, ok := du.mutation.AddedSourceIpStart(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpStart,
		})
	}
	if du.mutation.SourceIpStartCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: decision.FieldSourceIpStart,
		})
	}
	if value, ok := du.mutation.SourceIpEnd(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpEnd,
		})
	}
	if value, ok := du.mutation.AddedSourceIpEnd(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpEnd,
		})
	}
	if du.mutation.SourceIpEndCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: decision.FieldSourceIpEnd,
		})
	}
	if value, ok := du.mutation.SourceScope(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldSourceScope,
		})
	}
	if value, ok := du.mutation.SourceValue(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldSourceValue,
		})
	}
	if du.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.OwnerTable,
			Columns: []string{decision.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: alert.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.OwnerTable,
			Columns: []string{decision.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: alert.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{decision.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// DecisionUpdateOne is the builder for updating a single Decision entity.
type DecisionUpdateOne struct {
	config
	hooks    []Hook
	mutation *DecisionMutation
}

// SetCreatedAt sets the created_at field.
func (duo *DecisionUpdateOne) SetCreatedAt(t time.Time) *DecisionUpdateOne {
	duo.mutation.SetCreatedAt(t)
	return duo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableCreatedAt(t *time.Time) *DecisionUpdateOne {
	if t != nil {
		duo.SetCreatedAt(*t)
	}
	return duo
}

// SetUpdatedAt sets the updated_at field.
func (duo *DecisionUpdateOne) SetUpdatedAt(t time.Time) *DecisionUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetNillableUpdatedAt sets the updated_at field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableUpdatedAt(t *time.Time) *DecisionUpdateOne {
	if t != nil {
		duo.SetUpdatedAt(*t)
	}
	return duo
}

// SetUntil sets the until field.
func (duo *DecisionUpdateOne) SetUntil(t time.Time) *DecisionUpdateOne {
	duo.mutation.SetUntil(t)
	return duo
}

// SetScenario sets the scenario field.
func (duo *DecisionUpdateOne) SetScenario(s string) *DecisionUpdateOne {
	duo.mutation.SetScenario(s)
	return duo
}

// SetDecisionType sets the decisionType field.
func (duo *DecisionUpdateOne) SetDecisionType(s string) *DecisionUpdateOne {
	duo.mutation.SetDecisionType(s)
	return duo
}

// SetSourceIpStart sets the sourceIpStart field.
func (duo *DecisionUpdateOne) SetSourceIpStart(i int) *DecisionUpdateOne {
	duo.mutation.ResetSourceIpStart()
	duo.mutation.SetSourceIpStart(i)
	return duo
}

// SetNillableSourceIpStart sets the sourceIpStart field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableSourceIpStart(i *int) *DecisionUpdateOne {
	if i != nil {
		duo.SetSourceIpStart(*i)
	}
	return duo
}

// AddSourceIpStart adds i to sourceIpStart.
func (duo *DecisionUpdateOne) AddSourceIpStart(i int) *DecisionUpdateOne {
	duo.mutation.AddSourceIpStart(i)
	return duo
}

// ClearSourceIpStart clears the value of sourceIpStart.
func (duo *DecisionUpdateOne) ClearSourceIpStart() *DecisionUpdateOne {
	duo.mutation.ClearSourceIpStart()
	return duo
}

// SetSourceIpEnd sets the sourceIpEnd field.
func (duo *DecisionUpdateOne) SetSourceIpEnd(i int) *DecisionUpdateOne {
	duo.mutation.ResetSourceIpEnd()
	duo.mutation.SetSourceIpEnd(i)
	return duo
}

// SetNillableSourceIpEnd sets the sourceIpEnd field if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableSourceIpEnd(i *int) *DecisionUpdateOne {
	if i != nil {
		duo.SetSourceIpEnd(*i)
	}
	return duo
}

// AddSourceIpEnd adds i to sourceIpEnd.
func (duo *DecisionUpdateOne) AddSourceIpEnd(i int) *DecisionUpdateOne {
	duo.mutation.AddSourceIpEnd(i)
	return duo
}

// ClearSourceIpEnd clears the value of sourceIpEnd.
func (duo *DecisionUpdateOne) ClearSourceIpEnd() *DecisionUpdateOne {
	duo.mutation.ClearSourceIpEnd()
	return duo
}

// SetSourceScope sets the sourceScope field.
func (duo *DecisionUpdateOne) SetSourceScope(s string) *DecisionUpdateOne {
	duo.mutation.SetSourceScope(s)
	return duo
}

// SetSourceValue sets the sourceValue field.
func (duo *DecisionUpdateOne) SetSourceValue(s string) *DecisionUpdateOne {
	duo.mutation.SetSourceValue(s)
	return duo
}

// SetOwnerID sets the owner edge to Alert by id.
func (duo *DecisionUpdateOne) SetOwnerID(id int) *DecisionUpdateOne {
	duo.mutation.SetOwnerID(id)
	return duo
}

// SetNillableOwnerID sets the owner edge to Alert by id if the given value is not nil.
func (duo *DecisionUpdateOne) SetNillableOwnerID(id *int) *DecisionUpdateOne {
	if id != nil {
		duo = duo.SetOwnerID(*id)
	}
	return duo
}

// SetOwner sets the owner edge to Alert.
func (duo *DecisionUpdateOne) SetOwner(a *Alert) *DecisionUpdateOne {
	return duo.SetOwnerID(a.ID)
}

// Mutation returns the DecisionMutation object of the builder.
func (duo *DecisionUpdateOne) Mutation() *DecisionMutation {
	return duo.mutation
}

// ClearOwner clears the owner edge to Alert.
func (duo *DecisionUpdateOne) ClearOwner() *DecisionUpdateOne {
	duo.mutation.ClearOwner()
	return duo
}

// Save executes the query and returns the updated entity.
func (duo *DecisionUpdateOne) Save(ctx context.Context) (*Decision, error) {

	var (
		err  error
		node *Decision
	)
	if len(duo.hooks) == 0 {
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DecisionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DecisionUpdateOne) SaveX(ctx context.Context) *Decision {
	d, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return d
}

// Exec executes the query on the entity.
func (duo *DecisionUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DecisionUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DecisionUpdateOne) sqlSave(ctx context.Context) (d *Decision, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   decision.Table,
			Columns: decision.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: decision.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Decision.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := duo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: decision.FieldCreatedAt,
		})
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: decision.FieldUpdatedAt,
		})
	}
	if value, ok := duo.mutation.Until(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: decision.FieldUntil,
		})
	}
	if value, ok := duo.mutation.Scenario(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldScenario,
		})
	}
	if value, ok := duo.mutation.DecisionType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldDecisionType,
		})
	}
	if value, ok := duo.mutation.SourceIpStart(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpStart,
		})
	}
	if value, ok := duo.mutation.AddedSourceIpStart(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpStart,
		})
	}
	if duo.mutation.SourceIpStartCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: decision.FieldSourceIpStart,
		})
	}
	if value, ok := duo.mutation.SourceIpEnd(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpEnd,
		})
	}
	if value, ok := duo.mutation.AddedSourceIpEnd(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: decision.FieldSourceIpEnd,
		})
	}
	if duo.mutation.SourceIpEndCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: decision.FieldSourceIpEnd,
		})
	}
	if value, ok := duo.mutation.SourceScope(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldSourceScope,
		})
	}
	if value, ok := duo.mutation.SourceValue(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: decision.FieldSourceValue,
		})
	}
	if duo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.OwnerTable,
			Columns: []string{decision.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: alert.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   decision.OwnerTable,
			Columns: []string{decision.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: alert.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	d = &Decision{config: duo.config}
	_spec.Assign = d.assignValues
	_spec.ScanValues = d.scanValues()
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{decision.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return d, nil
}
