// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/crowdsecurity/crowdsec/cmd/api/ent/machine"
	"github.com/crowdsecurity/crowdsec/cmd/api/ent/signal"
	"github.com/facebook/ent/dialect/sql"
)

// Signal is the model entity for the Signal schema.
type Signal struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Scenario holds the value of the "scenario" field.
	Scenario string `json:"scenario,omitempty"`
	// BucketId holds the value of the "bucketId" field.
	BucketId string `json:"bucketId,omitempty"`
	// AlertMessage holds the value of the "alertMessage" field.
	AlertMessage string `json:"alertMessage,omitempty"`
	// EventsCount holds the value of the "eventsCount" field.
	EventsCount int `json:"eventsCount,omitempty"`
	// StartedAt holds the value of the "startedAt" field.
	StartedAt time.Time `json:"startedAt,omitempty"`
	// StoppedAt holds the value of the "stoppedAt" field.
	StoppedAt time.Time `json:"stoppedAt,omitempty"`
	// SourceIp holds the value of the "sourceIp" field.
	SourceIp string `json:"sourceIp,omitempty"`
	// SourceRange holds the value of the "sourceRange" field.
	SourceRange string `json:"sourceRange,omitempty"`
	// SourceAsNumber holds the value of the "sourceAsNumber" field.
	SourceAsNumber string `json:"sourceAsNumber,omitempty"`
	// SourceAsName holds the value of the "sourceAsName" field.
	SourceAsName string `json:"sourceAsName,omitempty"`
	// SourceCountry holds the value of the "sourceCountry" field.
	SourceCountry string `json:"sourceCountry,omitempty"`
	// SourceLatitude holds the value of the "sourceLatitude" field.
	SourceLatitude float32 `json:"sourceLatitude,omitempty"`
	// SourceLongitude holds the value of the "sourceLongitude" field.
	SourceLongitude float32 `json:"sourceLongitude,omitempty"`
	// Capacity holds the value of the "Capacity" field.
	Capacity int `json:"Capacity,omitempty"`
	// LeakSpeed holds the value of the "leakSpeed" field.
	LeakSpeed int `json:"leakSpeed,omitempty"`
	// Reprocess holds the value of the "reprocess" field.
	Reprocess bool `json:"reprocess,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SignalQuery when eager-loading is set.
	Edges           SignalEdges `json:"edges"`
	machine_signals *int
}

// SignalEdges holds the relations/edges for other nodes in the graph.
type SignalEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Machine
	// Decisions holds the value of the decisions edge.
	Decisions []*Decision
	// Events holds the value of the events edge.
	Events []*Event
	// Metas holds the value of the metas edge.
	Metas []*Meta
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SignalEdges) OwnerOrErr() (*Machine, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// The edge owner was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: machine.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// DecisionsOrErr returns the Decisions value or an error if the edge
// was not loaded in eager-loading.
func (e SignalEdges) DecisionsOrErr() ([]*Decision, error) {
	if e.loadedTypes[1] {
		return e.Decisions, nil
	}
	return nil, &NotLoadedError{edge: "decisions"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e SignalEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[2] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// MetasOrErr returns the Metas value or an error if the edge
// was not loaded in eager-loading.
func (e SignalEdges) MetasOrErr() ([]*Meta, error) {
	if e.loadedTypes[3] {
		return e.Metas, nil
	}
	return nil, &NotLoadedError{edge: "metas"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Signal) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},   // id
		&sql.NullTime{},    // created_at
		&sql.NullTime{},    // updated_at
		&sql.NullString{},  // scenario
		&sql.NullString{},  // bucketId
		&sql.NullString{},  // alertMessage
		&sql.NullInt64{},   // eventsCount
		&sql.NullTime{},    // startedAt
		&sql.NullTime{},    // stoppedAt
		&sql.NullString{},  // sourceIp
		&sql.NullString{},  // sourceRange
		&sql.NullString{},  // sourceAsNumber
		&sql.NullString{},  // sourceAsName
		&sql.NullString{},  // sourceCountry
		&sql.NullFloat64{}, // sourceLatitude
		&sql.NullFloat64{}, // sourceLongitude
		&sql.NullInt64{},   // Capacity
		&sql.NullInt64{},   // leakSpeed
		&sql.NullBool{},    // reprocess
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Signal) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // machine_signals
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Signal fields.
func (s *Signal) assignValues(values ...interface{}) error {
	if m, n := len(values), len(signal.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field created_at", values[0])
	} else if value.Valid {
		s.CreatedAt = value.Time
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field updated_at", values[1])
	} else if value.Valid {
		s.UpdatedAt = value.Time
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field scenario", values[2])
	} else if value.Valid {
		s.Scenario = value.String
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field bucketId", values[3])
	} else if value.Valid {
		s.BucketId = value.String
	}
	if value, ok := values[4].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field alertMessage", values[4])
	} else if value.Valid {
		s.AlertMessage = value.String
	}
	if value, ok := values[5].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field eventsCount", values[5])
	} else if value.Valid {
		s.EventsCount = int(value.Int64)
	}
	if value, ok := values[6].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field startedAt", values[6])
	} else if value.Valid {
		s.StartedAt = value.Time
	}
	if value, ok := values[7].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field stoppedAt", values[7])
	} else if value.Valid {
		s.StoppedAt = value.Time
	}
	if value, ok := values[8].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field sourceIp", values[8])
	} else if value.Valid {
		s.SourceIp = value.String
	}
	if value, ok := values[9].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field sourceRange", values[9])
	} else if value.Valid {
		s.SourceRange = value.String
	}
	if value, ok := values[10].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field sourceAsNumber", values[10])
	} else if value.Valid {
		s.SourceAsNumber = value.String
	}
	if value, ok := values[11].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field sourceAsName", values[11])
	} else if value.Valid {
		s.SourceAsName = value.String
	}
	if value, ok := values[12].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field sourceCountry", values[12])
	} else if value.Valid {
		s.SourceCountry = value.String
	}
	if value, ok := values[13].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field sourceLatitude", values[13])
	} else if value.Valid {
		s.SourceLatitude = float32(value.Float64)
	}
	if value, ok := values[14].(*sql.NullFloat64); !ok {
		return fmt.Errorf("unexpected type %T for field sourceLongitude", values[14])
	} else if value.Valid {
		s.SourceLongitude = float32(value.Float64)
	}
	if value, ok := values[15].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Capacity", values[15])
	} else if value.Valid {
		s.Capacity = int(value.Int64)
	}
	if value, ok := values[16].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field leakSpeed", values[16])
	} else if value.Valid {
		s.LeakSpeed = int(value.Int64)
	}
	if value, ok := values[17].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field reprocess", values[17])
	} else if value.Valid {
		s.Reprocess = value.Bool
	}
	values = values[18:]
	if len(values) == len(signal.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field machine_signals", value)
		} else if value.Valid {
			s.machine_signals = new(int)
			*s.machine_signals = int(value.Int64)
		}
	}
	return nil
}

// QueryOwner queries the owner edge of the Signal.
func (s *Signal) QueryOwner() *MachineQuery {
	return (&SignalClient{config: s.config}).QueryOwner(s)
}

// QueryDecisions queries the decisions edge of the Signal.
func (s *Signal) QueryDecisions() *DecisionQuery {
	return (&SignalClient{config: s.config}).QueryDecisions(s)
}

// QueryEvents queries the events edge of the Signal.
func (s *Signal) QueryEvents() *EventQuery {
	return (&SignalClient{config: s.config}).QueryEvents(s)
}

// QueryMetas queries the metas edge of the Signal.
func (s *Signal) QueryMetas() *MetaQuery {
	return (&SignalClient{config: s.config}).QueryMetas(s)
}

// Update returns a builder for updating this Signal.
// Note that, you need to call Signal.Unwrap() before calling this method, if this Signal
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Signal) Update() *SignalUpdateOne {
	return (&SignalClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Signal) Unwrap() *Signal {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Signal is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Signal) String() string {
	var builder strings.Builder
	builder.WriteString("Signal(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", scenario=")
	builder.WriteString(s.Scenario)
	builder.WriteString(", bucketId=")
	builder.WriteString(s.BucketId)
	builder.WriteString(", alertMessage=")
	builder.WriteString(s.AlertMessage)
	builder.WriteString(", eventsCount=")
	builder.WriteString(fmt.Sprintf("%v", s.EventsCount))
	builder.WriteString(", startedAt=")
	builder.WriteString(s.StartedAt.Format(time.ANSIC))
	builder.WriteString(", stoppedAt=")
	builder.WriteString(s.StoppedAt.Format(time.ANSIC))
	builder.WriteString(", sourceIp=")
	builder.WriteString(s.SourceIp)
	builder.WriteString(", sourceRange=")
	builder.WriteString(s.SourceRange)
	builder.WriteString(", sourceAsNumber=")
	builder.WriteString(s.SourceAsNumber)
	builder.WriteString(", sourceAsName=")
	builder.WriteString(s.SourceAsName)
	builder.WriteString(", sourceCountry=")
	builder.WriteString(s.SourceCountry)
	builder.WriteString(", sourceLatitude=")
	builder.WriteString(fmt.Sprintf("%v", s.SourceLatitude))
	builder.WriteString(", sourceLongitude=")
	builder.WriteString(fmt.Sprintf("%v", s.SourceLongitude))
	builder.WriteString(", Capacity=")
	builder.WriteString(fmt.Sprintf("%v", s.Capacity))
	builder.WriteString(", leakSpeed=")
	builder.WriteString(fmt.Sprintf("%v", s.LeakSpeed))
	builder.WriteString(", reprocess=")
	builder.WriteString(fmt.Sprintf("%v", s.Reprocess))
	builder.WriteByte(')')
	return builder.String()
}

// Signals is a parsable slice of Signal.
type Signals []*Signal

func (s Signals) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
