// Code generated by entc, DO NOT EDIT.

package machine

const (
	// Label holds the string label denoting the machine type in the database.
	Label = "machine"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMachineId holds the string denoting the machineid field in the database.
	FieldMachineId = "machine_id"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldIpAddress holds the string denoting the ipaddress field in the database.
	FieldIpAddress = "ip_address"

	// Table holds the table name of the machine in the database.
	Table = "machines"
)

// Columns holds all SQL columns for machine fields.
var Columns = []string{
	FieldID,
	FieldMachineId,
	FieldPassword,
	FieldToken,
	FieldIpAddress,
}
