// Code generated by entc, DO NOT EDIT.

package blocker

import (
	"time"
)

const (
	// Label holds the string label denoting the blocker type in the database.
	Label = "blocker"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldRevoked holds the string denoting the revoked field in the database.
	FieldRevoked = "revoked"
	// FieldIPAddress holds the string denoting the ip_address field in the database.
	FieldIPAddress = "ip_address"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldExpiration holds the string denoting the expiration field in the database.
	FieldExpiration = "expiration"
	// FieldLastPull holds the string denoting the last_pull field in the database.
	FieldLastPull = "last_pull"

	// Table holds the table name of the blocker in the database.
	Table = "blockers"
)

// Columns holds all SQL columns for blocker fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldAPIKey,
	FieldRevoked,
	FieldIPAddress,
	FieldType,
	FieldExpiration,
	FieldLastPull,
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// DefaultIPAddress holds the default value on creation for the ip_address field.
	DefaultIPAddress string
	// DefaultType holds the default value on creation for the type field.
	DefaultType string
	// DefaultLastPull holds the default value on creation for the last_pull field.
	DefaultLastPull func() time.Time
)
